platform: x64
clone_folder: c:\gopath\src\github.com\Tzunami\go-earthdollar
os: Visual Studio 2015
environment:
  GOPATH: c:\gopath
  GCP_PASSWD:
    secure: erzLJz7qT0kCJa+jZG6Sf9wwkfLYO2UDLzydkKTdwqA=
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

  # Install janus.
  - curl -sL https://raw.githubusercontent.com.earthdollarproject/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%

  - ps: $env:VERSION_BASE = "$(janus.exe version -format='v%M.%m.x')"
  - ps: $env:VERSION = "$(janus.exe version -format='TAG_OR_NIGHTLY')"

  - echo %VERSION_BASE% %VERSION%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get golang.org/x/sys/windows
build_script:
  - go test ./...
  - go build -ldflags "-X main.Version=%VERSION%" ./cmd/ged
  - 7z a ged-classic-win64-%VERSION%.zip ged.exe
artifacts:
  - path: '*.zip'
<<<<<<< HEAD
    name: ged
deploy:
  - provider: BinTray
    username: splix
    api_key:
      secure: yBy4Pe1aiUnBXLheSJNzRQxvVUm+g7etLEdKDWv82XvxAup4wg2nKZ/ogTyJkWxx
    subject: Tzunami
    repo: GoEarthdollarClassic
    package: go-earthdollar
    version: master
    publish: true
    override: true
    on:
      branch: master
  - provider: BinTray
    username: splix
    api_key:
      secure: yBy4Pe1aiUnBXLheSJNzRQxvVUm+g7etLEdKDWv82XvxAup4wg2nKZ/ogTyJkWxx
    subject: Tzunami
    repo: GoEarthdollarClassic
    package: go-earthdollar
    version: "%VERSION%"
    publish: true
    override: false
    on:
      appveyor_repo_tag: true
=======
    name: ged
before_deploy:
  # Set up GCP upload.
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt gcloud-appveyor.json.enc -secret %GCP_PASSWD% -out .gcloud.json
deploy_script:
  - ps: >-
      If ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
        janus.exe deploy -to="builds.etcdevteam.com/go.earthdollar/$env:VERSION_BASE/" -files="./*.zip" -key="./.gcloud.json"
      }

>>>>>>> 462a0c24946f17de60f3ba1226255a938bc47de3
